sonar.projectKey=smartsite-ml-prediction-service
sonar.projectName=SmartSite - ML Prediction Service
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/venv/**,**/test_*.py,**/*.pyc
sonar.python.version=3.14
